name = "newsnow"
pages_build_output_dir = "dist/output/public"
compatibility_date = "2024-10-28"

[vars]
G_CLIENT_ID = "Iv23li6mmcOFLbhR4Koz"
G_CLIENT_SECRET = "a9dfaf16613131bb52a083ff46458f88cfab72d0"
JWT_SECRET = "a9dfaf16613131bb52a083ff46458f88cfab72d0"
INIT_TABLE = true

[[d1_databases]]
binding = "NEWSNOW_DB"
database_name = "newsnow"
database_id = "63cd1383-de95-47b3-b147-deb3f57bb3e9"
